version: '3.9'

services:
  proxy-scraper:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "run.py"]
    ports:
      - "${HOST_PORT:-5000}:5000"
    restart: unless-stopped
